part of constants;

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'CHCP e-learning platform': 'CHCP e-learning platform',
          'Login': 'Login',
          'Guest': 'Guest',
          "Guest User": "Guest User",
          'Registration': 'Registration',
          'My Courses': 'My Courses',
          'Courses': 'Courses',
          'Module': 'Module',
          'Address': 'Address',
          'Enroll Course': 'Enroll Course',
          'Go to My Course': 'Go to My Course',
          'Enroll Student': 'Enroll Student',
          'Duration': 'Duration',
          'Lesson': 'Lesson',
          'Learning Objectives': 'Learning Objectives',
          'Support': 'Support',
          'Certificate': 'Certificate',
          'Resource': 'Resource',
          'Enter Course': 'Enter Course',
          'Quiz': 'Quiz',
          'Submit': 'Submit',
          'Next': 'Next',
          'Course Progress': 'Course Progress',
          'Previous': 'Previous',
          'Retake': 'Retake',
          'Profile': 'Profile',
          'Course Module': 'Course Module',
          'FAQ': 'FAQ',
          'User Guide': 'User Guide',
          'Training Manual': 'Training Manual',
          'N/A': 'N/A',
          'OK': 'OK',
          'Description': 'Description',
          'language': 'language',
          'Warning': 'Warning',
          'Success': 'Success',
          'Download Certificate': 'Download Certificate',
          'Change Password': 'Change Password',
          'Name': 'Name',
          'Password': 'Password',
          'HRM Email': 'HRM Email',
          'HRM Id': 'HRM Id',
          'Provider Id': 'Provider Id',
          'Phone': 'Phone',
          'Age': 'Age',
          'Gender': 'Gender',
          'Organization': 'Organization',
          'Designation': 'Designation',
          'Division': 'Division',
          'District': 'District',
          'Upazila': 'Upazila',
          'Continue': 'Continue',
          "Type Your Designation": "Type Your Designation",
          "Don't have an account ? ": "Don't have an account ? ",
          "Already have an account ? ": "Already have an account ? ",
          'Create new account': 'Create new account',
          "Development partner": 'Development partner',
          'Password is required': 'Password is required',
          'HRM Id is required': 'HRM Id is required',
          "Please input valid data": "Please input valid data",
          'HRM Id must include number': 'HRM Id must include number',
          'HRM Id minimum character is 3': 'HRM Id minimum character is 3',
          'Password minimum character is 3': 'Password minimum character is 3',
          'Password maximum character is 20':
              'Password maximum character is 20',
          "Designation is required": "Designation is required",
          'Designation minimum character is 3':
              'Designation minimum character is 3',
          'Phone Number': 'Phone Number',
          'Confirm password': 'Confirm password',
          'Full Name': 'Full Name',
          'Select Gender': 'Select Gender',
          'Organization Name': 'Organization Name',
          'Account': 'Account',
          'Confirm': 'Confirm',
          'New Password': 'New Password',
          'Old Password': 'Old Password',
          'Confirm Password is required': 'Confirm Password is required',
          'Password not Match': 'Password not Match',
          'Full Name is required': 'Full Name is required',
          'Full Name minimum character is 3':
              'Full Name minimum character is 3',
          'Division is required': 'Division is required',
          'Gender is required': 'Gender is required',
          'District is required': 'District is required',
          'Upazilla is required': 'Upazilla is required',
          'Organization is required': 'Organization is required',
          'Organization minimum character is 3':
              'Organization minimum character is 3',
          'Email is required': 'Email is required',
          'Age is required': 'Age is required',
          'Age must include number': 'Age must include number',
          'Phone No is required': 'Phone No is required',
          'Please enter valid mobile number':
              'Please enter valid mobile number',
          'Phone no at least 11 character': 'Phone no at least 11 character',
          'This access is not available for guest users':
              "This access is not available for guest users",
          'You have to complete previous module':
              'You have to complete previous module',
          'You have to complete previous sub module':
              'You have to complete previous sub module',
          'You have to complete the module': 'You have to complete the module',
          'Something Went Wrong': 'Something Went Wrong',
          'No Course Available': 'No Course Available',
          '<<Read Less': '<<Read Less',
          'Read More>>': 'Read More>>',
          'No Course Module Found': 'No Course Module Found',
          'You already passed this quiz': 'You already passed this quiz',
          'Your result': 'Your result',
          'Course complete': 'Course complete',
          "Quiz marks": "Quiz marks",
          'Frequently Asked Questions': 'Frequently Asked Questions',
          'No Course Enrolled': 'No Course Enrolled',
          'No Certificate Achived': 'No Certificate Achieved',
          '<Select Upazila>': '<Select Upazila>',
          '<Select District>': '<Select District>',
          '<Select Division>': '<Select Division>',
          'About Us': 'About Us',
          "Select your Center": "Select your Center",
          'Update Your Profile': 'Update Your Profile',
          'Next Module Unlocked >>': 'Next Module Unlocked >>',
          'Chose your correct answer': 'Chose your correct answer',
          'Quiz Has Been Submitted': 'Quiz Has Been Submitted',
          'Take the quiz again': 'Take the quiz again',
          'Questions': 'Questions',
          'out of': 'out of',
          "HRM Email is required": "HRM Email is required",
          "Invalid HRM Email": "Invalid HRM Email",
          "No internet connection.": "No internet connection.",
          "HTTP error occured.": "HTTP error occured.",
          "Invalid data format.": "Invalid data format.",
          "Request timedout.": "Request timedout.",
          "This is the last module": "This is the last module",
          "Mark Sheet": "Mark Sheet",
          "Quiz Mark": "Quiz Mark",
          "Trainer Guide": "Trainer Guide",
          "Preview Mark Sheet": "Preview Mark Sheet",
          "Enter your password": "Enter your password",
          "App Version - V0.0.1": "App Version - V0.0.1",
          "Please wait...": "Please wait...",
          "No Data Found": "No Data Found",
          "Course Completed": "Course Completed",
          "Logout": "Logout",
          "Cancel": "Cancel",
          "Are you sure, that you want to logout?":
              "Are you sure, that you want to logout?",
        },
        'bn_BD': {
          "No internet connection.": "ইন্টারনেট সংযোগ নেই",
          "HTTP error occured.": "HTTP ত্রুটি হয়েছে",
          "Invalid data format.": "Invalid data format.",
          "Request timedout.": "Request timedout.",
          'CHCP e-learning platform': 'CHCP ই-লার্নিং প্ল্যাটফর্ম',
          'Login': 'লগিন',
          'Guest': 'গেস্ট',
          "Guest User": "গেস্ট ইউজার",
          'Registration': 'রেজিস্ট্রেশন',
          'My Courses': 'আমার কোর্স',
          'Courses': 'কোর্স',
          'Module': 'মডিউল',
          'Enroll Course': 'নথিভুক্ত করুন',
          'Go to My Course': 'আমার কোর্স এ যান',
          'Enroll Student': 'নথিভুক্ত শিক্ষার্থী',
          'Learning Objectives': 'শিক্ষার উদ্দেশ্য',
          'Duration': 'কোর্স সময়কাল',
          'Lesson': 'শিক্ষামূলক বক্তৃতা',
          'Support': 'যোগাযোগ',
          'Course Progress': 'কোর্স অগ্রগতি',
          'Certificate': 'সার্টিফিকেট',
          'Download Certificate': 'ডাউনলোড সার্টিফিকেট',
          'Resource': 'রিসোর্স',
          'Enter Course': 'প্রবেশ করুন',
          'Quiz': 'কুইজ',
          'Submit': 'জমা দিন',
          'Address': 'ঠিকানা',
          'Next': 'পরবর্তী',
          'Previous': 'পূর্ববর্তী',
          'Retake': 'পুনরায়',
          'Profile': 'প্রোফাইল',
          'Course Module': 'কোর্স মডিউল',
          'FAQ': 'সচরাচর জিজ্ঞাস্য',
          'User Guide': 'নির্দেশিকা',
          'Training Manual': 'প্রশিক্ষণ ম্যানুয়াল',
          'N/A': 'নাই',
          'OK': 'ওকে',
          'Description': 'বর্ণনা',
          'language': 'ভাষা',
          'Warning': 'সতর্কতা',
          'Success': 'সফলতা',
          'Change Password': 'পাসওয়ার্ড পরিবর্তন করুন',
          'Change Your Password': 'আপনার পাসওয়ার্ড পরিবর্তন করুন',
          'Name': 'নাম',
          'Password': 'পাসওয়ার্ড',
          'HRM Email': 'HRM ইমেইল',
          'HRM Id': 'HRM আইডি',
          'Provider Id': 'প্রোভাইডার আইডি',
          'Designation Id': 'পদবি আইডি',
          'Phone': 'ফোন',
          'Age': 'বয়স',
          'Gender': 'লিঙ্গ',
          'Organization': 'সংস্থা',
          'Designation': 'পদবী',
          'Division': 'বিভাগ',
          'District': 'জেলা',
          'Upazila': 'উপজেলা',
          'Continue': 'চালিয়ে যান',
          'Password is required': 'পাসওয়ার্ড প্রদান করতে হবে',
          'HRM Id is required': 'HRM আইডি প্রয়োজন',
          "Type Your Designation": "আপনার পদবী টাইপ করুন",
          "Don't have an account ? ": "যদি একাউন্ট না থাকে ? ",
          "Already have an account ? ": "যদি অ্যাকাউন্ট থেকে থাকে ? ",
          'Create new account': 'নতুন অ্যাকাউন্ট তৈরি করুন',
          "Development partner": 'উন্নয়ন সহযোগী',
          "Please input valid data": "অনুগ্রহ করে বৈধ ডেটা ইনপুট করুন",
          'HRM Id must include number':
              'HRM আইডিতে অবশ্যই নম্বর অন্তর্ভুক্ত করতে হবে',
          'HRM Id minimum character is 3':
              'HRM আইডিতে ন্যূনতম ৩ টি অক্ষর প্রয়োজন',
          'Password minimum character is 3':
              'পাসওয়ার্ড এ ন্যূনতম ৩ টি অক্ষর প্রয়োজন',
          'Password maximum character is 20':
              'পাসওয়ার্ড এ সর্বোচ্চ ২০ টি অক্ষর প্রয়োজন',
          "Designation is required": "পদবী প্রয়োজন",
          'Designation minimum character is 3':
              'পদবীতে ন্যূনতম ৩ টি অক্ষর প্রয়োজন',
          'Phone Number': 'ফোন নম্বর',
          'Confirm password': 'নিশ্চিতকরন পাসওয়ার্ড',
          'Course complete': 'কোর্স সম্পূর্ণ হয়েছে',
          'Full Name': 'সম্পূর্ণ নাম',
          'Select Gender': 'লিংগ নির্বাচন করুন',
          'Organization Name': 'প্রতিষ্ঠানের নাম',
          'Account': 'অ্যাকাউন্ট',
          'Confirm': 'কনফার্ম করুন',
          'New Password': 'নতুন পাসওয়ার্ড',
          'Old Password': 'পুরানো পাসওয়ার্ড',
          'Confirm Password is required': 'পুনরায় পাসওয়ার্ড দিন',
          'Password not Match': 'পাসওয়ার্ড সঠিক নয়',
          'Full Name is required': 'সম্পূর্ণ নাম প্রদান করতে হবে',
          "HRM Email is required": "HRM ইমেইল প্রদান করতে হবে",
          "Invalid HRM Email": "ইমেইল সঠিক নয়",
          'Full Name minimum character is 3':
              'সম্পূর্ণ নামে নূন্যতম ৩ টি অক্ষর প্রয়োজন',
          'Division is required': 'বিভাগ প্রদান করতে হবে',
          'Gender is required': 'লিঙ্গ প্রদান করতে হবে',
          'District is required': 'জেলা প্রদান করতে হবে',
          'Upazilla is required': 'উপজেলা প্রদান করতে হবে',
          'Organization is required': 'প্রতিষ্ঠানের নাম প্রদান করতে হবে',
          'Organization minimum character is 3':
              'প্রতিষ্ঠান এ নূন্যতম ৩ টি অক্ষর প্রয়োজন',
          'Email is required': 'ইমেইল প্রদান করতে হবে',
          'Age is required': 'বয়স প্রদান করতে হবে',
          'Age must include number': 'বয়স এ অবশ্যই নম্বর অন্তর্ভুক্ত করতে হবে',
          'Phone No is required': 'ফোন নম্বর প্রদান করতে হবে',
          'Please enter valid mobile number':
              'অনুগ্রহ করে সঠিক মোবাইল নম্বর লিখুন',
          'Phone no at least 11 character':
              'ফোন নম্বর কমপক্ষে ১১ অক্ষর প্রয়োজন',
          'This access is not available for guest users':
              'এই অ্যাক্সেস গেস্ট ব্যবহারকারীদের জন্য উপলব্ধ নয়',
          'You have to complete previous module':
              'আপনাকে আগের সাব মডিউলটি সম্পূর্ণ করতে হবে',
          'You have to complete previous sub module':
              'আপনাকে আগের সাব মডিউলটি সম্পূর্ণ করতে হবে',
          'You have to complete the module': 'আপনাকে মডিউলটি সম্পূর্ণ করতে হবে',
          'Something Went Wrong': 'কোথাও ভুল হয়েছে',
          'No Course Available': 'কোন কোর্স পাওয়া যায়নি',
          'No Certificate Achieved': 'কোন সার্টিফিকেট অর্জন করা হয়নি',
          '<<Read Less': '<<Read Less',
          'Read More>>': 'Read More>>',
          'No Course Module Found': 'কোন কোর্স মডিউল পাওয়া যায়নি',
          'You already passed this quiz': 'আপনি ইতিমধ্যে এই কুইজ পাস করেছেন',
          'Your result': 'আপনার ফলাফল',
          "Quiz marks": "কুইজ মার্ক্স্",
          'Frequently Asked Questions': 'সচরাচর জিজ্ঞাস্য',
          'No Course Enrolled': 'কোন কোর্স নথিভুক্ত নয়',
          '<Select Upazila>': '<Sমার্ক্স্elect Upazila>',
          '<Select District>': '<Select District>',
          '<Select Division>': '<Select Division>',
          'About Us': 'আমাদের সম্পর্কে',
          "Select your Center": "আপনার কেন্দ্র নির্বাচন করুন",
          'Center Is Required': 'কেন্দ্র প্রদান করতে হবে',
          'Update Your Profile': 'আপনার প্রোফাইল আপডেট করুন',
          'Next Module Unlocked >>': 'পরবর্তী মডিউল আনলক হয়েছে',
          'Chose your correct answer': 'আপনার সঠিক উত্তর বাছাই করুন',
          'Quiz Has Been Submitted': 'কুইজ জমা দেওয়া হয়েছে',
          'Take the quiz again': 'আবার কুইজ দিন',
          "This is the last module": "এটি শেষ মডিউল",
          'Questions': 'প্রশ্ন',
          'out of': 'হতে',
          "Trainer Guide": "প্রশিক্ষক গাইড",
          "Mark Sheet": "মার্কশিট",
          "Quiz Mark": "কুইজ নম্বর",
          "Preview Mark Sheet": "মার্কশিট দেখুন",
          "Enter your password": "আপনার পাসওয়ার্ড লিখুন",
          "App Version - V0.0.1": "অ্যাপ ভার্সন - V0.0.1",
          "Please wait...": "অনুগ্রহ করে অপেক্ষা করুন...",
          "No Data Found": "কোন তথ্য পাওয়া যায়নি",
          "Course Completed": "কোর্সটি সম্পন্ন হয়েছে",
          "Logout": "লগ আউট",
          "Cancel": "বাতিল করুন",
          "Are you sure, that you want to logout?":
              "আপনি কি নিশ্চিত, আপনি এখন লগ আউট করতে চান?",
        }
      };
}
